In [1]:
import numpy as np

1. Utwórz NumPy array na podstawie podanej listy wartosci. Następnie utwórz drugi array, w którym będą wyłącznie wartości nieparzyste.

In [2]:
data = [1, 21, 35, 10, 20, 54, 61, 98, 99, 10003]

In [3]:
data_1 = np.array(data)

In [4]:
data_2 = np.array([x for x in data_1 if x % 2])
data_2

array([    1,    21,    35,    61,    99, 10003])

2. Elementy tablicy z wartościami nieparzystymi podziel przez 11. Następnie wypisz najmniejszą z wynikowych wartości.

In [5]:
data_3 = np.min(data_2 / 11)
data_3

0.09090909090909091

3. Utwórz NumPy array na podstawie podanej listy wartosci. Dokonaj normalizacji do zakresu `[0, 1]`, tj. przelicz wartości tak aby minimalna wartość wyniosła 0, maksymalna 1, a wszystkie pozostałe były odpowiednio pomiędzy.

In [6]:
data = [5, 21, 35, 10, 20, 7, 54, 61, 98, 99, 120]

In [7]:
data_array = np.array(data)
data_array

array([  5,  21,  35,  10,  20,   7,  54,  61,  98,  99, 120])

In [8]:
# Obliczenie minimalnej i maksymalnej wartości
min_value = np.min(data_array)
max_value = np.max(data_array)

In [9]:
# Dokonanie normalizacji
norm_data_array = (data_array - min_value) / (max_value - min_value)
norm_data_array

array([0.        , 0.13913043, 0.26086957, 0.04347826, 0.13043478,
       0.0173913 , 0.42608696, 0.48695652, 0.80869565, 0.8173913 ,
       1.        ])

4. Dla podanej tablicy dokonaj przycięcia wartości do zakresu `[100, 200]`, tj. wartości mniejsze niż 100 powinny przyjać wartość 100, większe niż 200 - 200, a reszta bez zmiany.
Wykonaj zadanie na dwa sposoby:
a. Przypisując wartości z odpowiednim warunkiem
b. Wykorzystując funkcję `np.clip` https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [10]:
data_b = np.random.randint(0,250,20)
data_b

array([ 23,  71,  81,  45, 183, 215,  49,  53, 103, 235,  99,  78,  45,
       238, 132,  28, 182, 119, 249, 144])

In [11]:
# wartości z warunkiem 
data_c = np.array([100 if x < 100 else 200 if x > 200 else x for x in data_b])
data_c

array([100, 100, 100, 100, 183, 200, 100, 100, 103, 200, 100, 100, 100,
       200, 132, 100, 182, 119, 200, 144])

In [12]:
# funkcja np.clip
data_d = np.clip(data_b, 100, 200)
data_d

array([100, 100, 100, 100, 183, 200, 100, 100, 103, 200, 100, 100, 100,
       200, 132, 100, 182, 119, 200, 144])

5. Dla podanej tablicy podaj wartość maksymalną każdego wiersza. Wynik powinien mieć postać NumPy array
a. Spróbuj poradzić sobie pętlą `for`
b. Wykorzystaj metodę `max` (lub funkcję `amax`) z argumentem opcjonalnym `axis` https://numpy.org/doc/stable/reference/generated/numpy.amax.html

In [13]:
data_e = np.random.randint(1,10, [5,3])
data_e

array([[5, 9, 6],
       [7, 3, 3],
       [2, 4, 3],
       [5, 6, 6],
       [5, 8, 7]])

In [14]:
# z pętlą for
max_value_a = np.array([max(row) for row in data_e])
max_value_a

array([9, 7, 4, 6, 8])

In [15]:
# z amax
max_value_b = np.amax(data_e, axis=1)
max_value_b

array([9, 7, 4, 6, 8])

6. Dla podanej tablicy policz sumę wartości w każdym wierszu. Następnie policz średnią tych sum.

In [16]:
data_f = np.random.randint(1,10, [5,3])
data_f

array([[1, 2, 3],
       [5, 8, 3],
       [5, 3, 3],
       [8, 6, 7],
       [2, 9, 2]])

In [17]:
data_sum = np.sum(data_f, axis=1)
data_sum

array([ 6, 16, 11, 21, 13])

In [18]:
data_ave = np.mean(data_sum)
data_ave

13.4

7. Utwórz wektor numpy zawierający poniższe dane.

In [19]:
dane = [255, 255, 120, 240, 0]
dane_array = np.array(dane)
dane_array

array([255, 255, 120, 240,   0])

8. Utwórz wektor `values` zawierający pierwsze 4 wartości. Utwórz zmienną `target` zawierajacą ostatnią, piątą, wartość.

In [20]:
values = dane_array[:4]
values

array([255, 255, 120, 240])

In [21]:
target = dane_array[4]
target 

0

9. Przekształć wektor `values` na macierz 2x2 i przedstaw dane jako para `(values, target)` pod zmienną `sample`

In [22]:
values = values.reshape(2,2)
values

array([[255, 255],
       [120, 240]])

In [23]:
sample = (values, target)
sample

(array([[255, 255],
        [120, 240]]),
 0)

10. Wykonaj operacje z zadań 2 i 3 na danych z listy (pierwsze 4 wartości do macierzy 2x2, a ostatnia jako osobna wartość). Utwórz na jej podstawie listę `samples`, która będzie zawierała pary `(values, target)`

In [24]:
dane_lista = [
   [255, 255, 120, 240, 0],
   [250, 25, 120, 0, 0],
   [255, 255, 10, 200, 0],
   [255, 15, 120, 100, 0],
   [200, 255, 255, 255, 1]
]

In [25]:
dane_array = np.array(dane_lista)
dane_array

array([[255, 255, 120, 240,   0],
       [250,  25, 120,   0,   0],
       [255, 255,  10, 200,   0],
       [255,  15, 120, 100,   0],
       [200, 255, 255, 255,   1]])

In [26]:
values_dane = dane_array[:4].reshape(-1,2,2)
values_dane

array([[[255, 255],
        [120, 240]],

       [[  0, 250],
        [ 25, 120]],

       [[  0,   0],
        [255, 255]],

       [[ 10, 200],
        [  0, 255]],

       [[ 15, 120],
        [100,   0]]])

In [27]:
target_dane = dane_array[:, 4]
target_dane

array([0, 0, 0, 0, 1])

In [28]:
samples = list(zip(values_dane, target_dane))
samples

[(array([[255, 255],
         [120, 240]]),
  0),
 (array([[  0, 250],
         [ 25, 120]]),
  0),
 (array([[  0,   0],
         [255, 255]]),
  0),
 (array([[ 10, 200],
         [  0, 255]]),
  0),
 (array([[ 15, 120],
         [100,   0]]),
  1)]

11. Odejmij `mat_1` od `mat_2`. Uzyskaj wartość bezwzględną wszystkich elementów wynikowej macierzy i zapisz do zmiennej `wynik`

In [29]:
mat_1 = np.array([[2, 4, 15], [3, 9, 6], [4, 8, 12]])
mat_2 = np.array([[6, 9, 1], [13, 2, 6], [7, 8, 12]])

In [30]:
mat = mat_1 - mat_2
mat

array([[ -4,  -5,  14],
       [-10,   7,   0],
       [ -3,   0,   0]])

In [31]:
result = np.abs(mat)
result

array([[ 4,  5, 14],
       [10,  7,  0],
       [ 3,  0,  0]])

12. Podnieś do kwadratu te elementy zmiennej `wynik`, które są mniejsze od 6.

In [32]:
result[result < 6] = result[result < 6] ** 2
result

array([[16, 25, 14],
       [10,  7,  0],
       [ 9,  0,  0]])